# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."  # <-- add .exe
  bin = "tmp/main.exe"                  # <-- add .exe here too
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
